### ISSUE TITLE
Automate GitHub Runner Container Image Build

### ISSUE THREAD

**Issue by dwinchell** [ploigos/github-runners#1]
Success Criteria:
* When I push a change to the Containerfile in the github-runners project, a GitHub actions workflow builds a new image with those changes
* The image is pushed to the public repository - quay.io/ploigos/ploigos-github-runner
* The workflow pushes to different image tags, based on branch
    * main branch in github -> :latest tag in quay
    * feature/* branch in github -> feature-* branch in quay

Notes:
* See the ploigos/ploigos-containers repo for an example GitHub actions workflow that might help
* Until we have access to quay.io/ploigos, we can temporarily use a personal quay.io organization

References
- https://www.redhat.com/en/blog/build-ubi-containers-github-actions-buildah-and-podman
- https://github.com/redhat-actions/buildah-build

**Comment by aarongreen85** [comment]
Found these 2 actions on the marketplace that I think we'll get us what we need -

https://github.com/marketplace/actions/buildah-build
https://github.com/marketplace/actions/push-to-registry

**Comment by dwinchell** [comment]
This might be useful: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
