### ISSUE TITLE
Stretch - Use Artifactory for our github runner image

### ISSUE THREAD

**Issue by dwinchell** [ploigos/github-runners#23]
Success Criteria:
* The workflow that builds the GitHub runner image pushes it to Artifactory
* The deployment of GitHub runner in OpenShift uses the image from Artifactory

Note:
* Existing pipeline runs on a GitHub-hosted runner
* The pipeline will need credentials to push to Artifactory
    * We could solve this by putting the credentials in a GitHub Actions Secret
    * We *could* instead build the image on our self-hosted runner using ploigos, which would allow us to easily pull the Artifactory credentials from Vault

**Comment by aarongreen85** [comment]
This portion is completed - The deployment of GitHub runner in OpenShift uses the image from Artifactory.

This portion was decided against - The workflow that builds the GitHub runner image pushes it to Artifactory. It's desired that the github-runner image remain upstream for others use as well. If additional modifications are needed for use, the resulting image could be pushed directly to a private registry.
